#:schema node_modules/wrangler/config-schema.json
name = "zefpesublink"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "08679be80462448ab8d68c0a1c328527" }
]

[assets]
directory = "./public"
